version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    volumes:
      - data1:/var/jenkins_home
    networks:
      - bridg
    ports:
      - "8080:8080"
  jenkins2:
    image: jenkins/jenkins
    container_name: jenkins2
    volumes:
      - data2:/var/jenkins_home
    networks:
      - bridg2
    ports:
      - "8090:8080"
  bitbucket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitbucket
    networks:
      - bridg
      - bridg2
    ports:
      - "7990:7990"
      - "7999:7999"
      - "5005:5005"
    volumes:
      - bit-data:/var/atlassian/application-data/bitbucket
    environment:
      JVM_SUPPORT_RECOMMENDED_ARGS: -Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n

volumes:
  docker-cert:
    external: false
  data1:
    external: false
  data2:
    external: false
  bit-data:
    external: false

networks:
  bridg:
    driver: bridge
  bridg2:
    driver: bridge
